### ISSUE TITLE
Not support unicode text

### ISSUE THREAD

**Issue by nutinshell** [posativ/regenwolken#33]
Unicode text like Chinese can be uploaded but display garbled chars, but it's fine in direct link(view raw).

**Comment by posativ** [comment]
I can not offer a quick fix for this as I am not familiar with unicode/chinese urls. I've seen an issue in werkzeug where it was not capable of handling cyrillic letters. I'll investigate later.

**Comment by posativ** [comment]
It's broken with german umlauts, too. What a pity.

**Comment by posativ** [comment]
Should be fixed now!
