### ISSUE TITLE
Cannot use sudo with echo

### ISSUE THREAD

**Issue by kseistrup** [posativ/regenwolken#42]
The instructions say:

``` sh
$ sudo echo "12.34.56.78 my.cl.ly" >> /etc/hosts
```

However, you cannot use sudo with echo this way because the shell sets up redirection before root privileges have been granted.  Instead you should

``` sh
$ echo "12.34.56.78 my.cl.ly" | sudo tee -a /etc/hosts
```

or

``` sh
$ sudo sh -c 'echo "12.34.56.78 my.cl.ly" >> /etc/hosts'
```

or similar.

**Comment by posativ** [comment]
Thanks, pushed the `tee` version to master.
