### ISSUE TITLE
Not working with apache2 / mod_proxy

### ISSUE THREAD

**Issue by otherguy** [posativ/regenwolken#43]
Could also be an issue with my setup but I have no idea how to debug it (are there any logs?).

My setup is Debian/Apache2 and most recent Regenwolken as per your deploy instructions.

Apache is configured with:

``` ApacheConf
ProxyPass / http://127.0.0.1:3000/
ProxyPassReverse / http://127.0.0.1:3000/
```

This works well for registration and login. Upon login I get:

```
127.0.0.1 - - [20/Dec/2013 20:45:50] "GET /account HTTP/1.1" 401 12
127.0.0.1 - - [20/Dec/2013 20:45:50] "GET /account HTTP/1.1" 200 348
127.0.0.1 - - [20/Dec/2013 20:45:50] "GET /items?page=1&per_page=20&deleted=false HTTP/1.1" 401 12
127.0.0.1 - - [20/Dec/2013 20:45:50] "GET /items?page=1&per_page=20&deleted=false HTTP/1.1" 200 2
```

and the latest CloudApp client (official) for Mac claims it's logged in. That's about it, though.

Uploading files gives me this (small 10kb JPG):

```
127.0.0.1 - - [20/Dec/2013 20:50:01] "GET /items/new HTTP/1.1" 401 12
127.0.0.1 - - [20/Dec/2013 20:50:01] "GET /items/new HTTP/1.1" 200 161
```

and CloudApp claims that upload failed.

When I click "Open web interface" I get sent to http://my.cl.ly/mac which brings up a 404 error and Regenwolken says:

```
127.0.0.1 - - [20/Dec/2013 20:51:01] "GET /mac HTTP/1.1" 401 12
127.0.0.1 - - [20/Dec/2013 20:51:01] "GET /mac HTTP/1.1" 404 233
```

Going directly to my configured domain (or to http://my.cl.ly/) first gives me a HTTP Basic Auth popup, where I can log in with my credentials. Then I get a 500 Server Error while Regenwolken says:

```
127.0.0.1 - - [20/Dec/2013 20:51:42] "GET / HTTP/1.1" 500 291
127.0.0.1 - - [20/Dec/2013 20:51:42] "GET / HTTP/1.1" 500 291
```

Any help would be appreciated. I just can't seem to find any logs where I could further debug the issue.

Thanks!

**Comment by posativ** [comment]
Hi,

first I do not use Apache. I moved from OS X to Linux now but what seems weird to me:
- when Cloud.app requests an upload token, it issues a GET request to `/items/new` and _then_ POSTs to `/` which is not logged (did you omit this part?)
- a 500 server error on the index page should not happen unless MongoDB has an unexpected shutdown (which happens quite often for no particular reasons imho). You can fix this by running `rwctl --conf=/.../rw.conf repair`.

Also, you can enable logging to file via `LOGFILE = "/path/to/rw.log"`.

**Comment by otherguy** [comment]
Hey,

thanks for the help :) The server (regenwolken) itself is running on Debian 7.2 only the client is CloudApp for OS X. I tried with different clients too, but I get the same result.

Whether the requests are proxied through Apache or lighttpd should not make a difference. Unfortunately, Apache already handles several websites on that server so a switch to lighttpd would be a pretty big thing. 

I'm monitoring the MongoDB instance and there were no unexpected crashes/shutdowns.

## Upload tokens

> when Cloud.app requests an upload token, it issues a GET request to /items/new and then POSTs to / which is not logged (did you omit this part?)

No, I didn't omit a thing. But your remark got me thinking and I discovered a typo in the HOSTNAME setting. Once that was fixed, uploads of images started working. Thank you! :+1: 

However, the uploaded file cannot be viewed and I get the same 500 Server Error I also get on the index page.

## Error 500 on index

Enabling error logging was helpful here too: Oddly enough, the 500 error on the index page seems to be due to a missing template.

``` python
2013-12-23 16:11:02,198 ERROR: Exception on / [GET] [in /usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py:1423]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/regenwolken/views.py", line 62, in index
    return Response(render_template("index.html", **locals()), 200, content_type="text/html")
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python2.7/dist-packages/Jinja2-2.7.1-py2.7.egg/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python2.7/dist-packages/Jinja2-2.7.1-py2.7.egg/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python2.7/dist-packages/Jinja2-2.7.1-py2.7.egg/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python2.7/dist-packages/Jinja2-2.7.1-py2.7.egg/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: index.html
```

**Comment by otherguy** [comment]
I just reinstalled Regenwolken using the commands on the Deployment help page:

```
pip install regenwolken  # or master from GitHub
pip install --upgrade git+git://github.com/posativ/regenwolken.git#egg=regenwolken
```

and noticed this:

```
Downloading/unpacking regenwolken
  Downloading regenwolken-0.6.1.tar.gz
  Running setup.py egg_info for package regenwolken

    warning: manifest_maker: MANIFEST.in, line 2: 'recursive-include' expects <dir> <pattern1> <pattern2> ...

    warning: no files found matching '*' under directory 'regenwolken/templates/'
Requirement already satisfied (use --upgrade to upgrade): flask>=0.8 in /usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg (from regenwolken)
Requirement already satisfied (use --upgrade to upgrade): pymongo in /usr/local/lib/python2.7/dist-packages/pymongo-2.6.3-py2.7-linux-x86_64.egg (from regenwolken)
Requirement already satisfied (use --upgrade to upgrade): Werkzeug>=0.7 in /usr/local/lib/python2.7/dist-packages/Werkzeug-0.9.4-py2.7.egg (from flask>=0.8->regenwolken)
Requirement already satisfied (use --upgrade to upgrade): Jinja2>=2.4 in /usr/local/lib/python2.7/dist-packages/Jinja2-2.7.1-py2.7.egg (from flask>=0.8->regenwolken)
Requirement already satisfied (use --upgrade to upgrade): itsdangerous>=0.21 in /usr/local/lib/python2.7/dist-packages/itsdangerous-0.23-py2.7.egg (from flask>=0.8->regenwolken)
Requirement already satisfied (use --upgrade to upgrade): markupsafe in /usr/local/lib/python2.7/dist-packages/MarkupSafe-0.18-py2.7.egg (from Jinja2>=2.4->flask>=0.8->regenwolken)
Installing collected packages: regenwolken
  Running setup.py install for regenwolken

    warning: manifest_maker: MANIFEST.in, line 2: 'recursive-include' expects <dir> <pattern1> <pattern2> ...

    warning: no files found matching '*' under directory 'regenwolken/templates/'
    warning: install_data: setup script did not provide a directory for 'README.md' -- installing right in '/usr/local/lib/python2.7/dist-packages'

    warning: install_data: setup script did not provide a directory for 'LICENSE.txt' -- installing right in '/usr/local/lib/python2.7/dist-packages'

    Installing regenwolken script to /usr/local/bin
    Installing rwctl script to /usr/local/bin
Successfully installed regenwolken
Cleaning up...
```

Seems like a problem with the install script. I put the _templates_ and _static_ folders in the right places manually and now it's working fine!

Maybe you can figure out what's wrong with the install script. I'm not a python guy so I really couldn't say.

Anyway, thanks again for your help and for writing Regenwolken! :) It seems like a great piece of software.

**Comment by posativ** [comment]
The warning is indeed suspicious. I uses a suboptimal way to include assets into the package for regenwolken (it is  an older project). I removed a hack and fixed the MANIFEST.in in e6f419c85a98eaea17af1cac915e07cf2755c423 which should fix the warning (on my system it installs the assets correctly).

Thank you for your help.
