### ISSUE TITLE
no upload progress

### ISSUE THREAD

**Issue by posativ** [posativ/regenwolken#5]
the default app has a progress bar, when uploading... some callback or whatever. We need it, too! (maybe related to their S3/my.cl.ly split)

**Comment by cmur2** [comment]
I have seen such an upload bar on the client side recently... seems that this part has worked sometime...

**Comment by cmur2** [comment]
Upload progress in CloudApp works for me (self filling cloud from the right) on Lion.

**Comment by posativ** [comment]
can confirm.
